name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: login-ok
      id: login-ok
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: login-ok
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 01-login-ok.js
        timeout: 10
        max-score: 1
    - name: login-error-pwd
      id: login-error-pwd
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: login-error-pwd
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 02-login-error-pwd.js
        timeout: 10
        max-score: 1
    - name: login-error-user
      id: login-error-user
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: login-error-user
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 03-login-error-user.js
        timeout: 10
        max-score: 1
    - name: register-error-pwd
      id: register-error-pwd
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: register-error-pwd
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 04-register-error-pwd.js
        timeout: 10
        max-score: 1
    - name: register-ok
      id: register-ok
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: register-ok
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 05-register-ok.js
        timeout: 10
        max-score: 1
    - name: register-error-username
      id: register-error-username
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 06-register-error-username
        setup-command: sudo apt update ; sudo apt install -y nodejs ; sudo npm install
          -g cordova ; cordova platform add browser ; sudo snap remove firefox ; sudo
          apt install software-properties-common -y ; sudo add-apt-repository -y ppa:mozillateam/ppa
          ; sudo apt install firefox-esr
        command: cd .test ; npm install ; node 06-register-error-username.js
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LOGIN-OK_RESULTS: "${{steps.login-ok.outputs.result}}"
        LOGIN-ERROR-PWD_RESULTS: "${{steps.login-error-pwd.outputs.result}}"
        LOGIN-ERROR-USER_RESULTS: "${{steps.login-error-user.outputs.result}}"
        REGISTER-ERROR-PWD_RESULTS: "${{steps.register-error-pwd.outputs.result}}"
        REGISTER-OK_RESULTS: "${{steps.register-ok.outputs.result}}"
        REGISTER-ERROR-USERNAME_RESULTS: "${{steps.register-error-username.outputs.result}}"
      with:
        runners: login-ok,login-error-pwd,login-error-user,register-error-pwd,register-ok,register-error-username
